### ISSUE TITLE
Latest update breaks functionality

### ISSUE THREAD

**Issue by onyxnz** [backdrop-contrib/maillog#10]
Update 1101 breaks the DB functionality by not updating the first column from 'idmaillog' to the 'id' it now expects in the install file. However in maillog_cron it's still 'idmaillog'.
Error:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'field list': INSERT INTO {maillog} (`id`, `header_message_id`, `header_from`, `header_to`, `header_reply_to`, `header_all`, `subject`, `body`, `sent_date`) VALUES  ....

**Comment by herbdool** [comment]
@laryn looks like a bug.

**Comment by yorkshire-pudding** [comment]
It looks like the latest update imported from D7 changed the ID column from `idmaillog` to `id` but the update hook didn't change the schema to match as the field is still `idmaillog`.

**Comment by laryn** [comment]
Thanks for the report. Yes, @yorkshire-pudding exactly right. Mea culpa during the merge process to get latest Drupal 7 commits over here.

@onyxnz are you able to test the PR here? 
https://github.com/backdrop-contrib/maillog/pull/11

**Comment by laryn** [comment]
I did ensure that the tests ran locally before last release, but I guess the tests don't cover: upgrading or cron. 😆

**Comment by onyxnz** [comment]
Have tested with your latest. All good, thanks @laryn
