### ISSUE TITLE
Unable to get the system to register mail

### ISSUE THREAD

**Issue by onyxnz** [backdrop-contrib/maillog#8]
In trying to diagnose a failure with sending of some emails, I found and added this module. This module installs fine, and appears to function, but system emails, whether via Rules or Account Creation/Change Password are not logged.
The log merely shows:
Maillog
Maillog is currently empty. Send a mail!

**Comment by laryn** [comment]
@onyxnz I just installed a demo site and installed Maillog, then tried to reset the password. It shows up in the Maillog. Can you provide steps to reproduce on a demo server?

**Comment by argiepiano** [comment]
@onyxnz check `system.mail.json` to see which class your site is using for emails. If it's set to `TestingMailSystem` then any email sent by the site (regardless of whether you have `maillog` or not) will not be sent. They are saved to `test_email_collector` in the `state` database table to allow for testing. 

Also check to see if you have any other mail contrib modules like MimeMail or Mailsystem.

EDIT: I see in the module's description that they recommend either manually editing that json file, or using mailsystem to select the class `MaillogMailSystem` for `default-system` in the json file.

**Comment by onyxnz** [comment]
My system mail json:
{
    "_config_name": "system.mail",
    "default-system": "MimeMailSystem",
    "user_import": "DefaultMailSystem",
    "uc_cart": "UbercartMailSystem",
    "uc_order": "UbercartMailSystem",
    "uc_file": "UbercartMailSystem",
    "uc_roles": "UbercartMailSystem",
    "uc_stock": "UbercartMailSystem",
    "uc_store": "UbercartMailSystem",
    "mimemail": "MimeMailSystem",
    "mail_system": {
        "default-system": "SendGridMailSystem"
    }
}

So should I try "default-system": "MimeMailSystem" , and therefore bypass the sendgrid system?

**Comment by onyxnz** [comment]
I have fixed the initial problem that necessitated the installation of this module, as per:
https://forum.backdropcms.org/forum/mail-logging#comment-5575

but as @laryn says, will look at setup of this module in a more vanilla environment at another time; I suspect SendGrid module is bypassing it, despite these settings:
![image](https://github.com/backdrop-contrib/maillog/assets/118966871/e91d6815-b09b-419f-99ad-f1a0da348834)

**Comment by onyxnz** [comment]
with my system.mail.json like the following, I am able to get logs in Maillog!

{
    "_config_name": "system.mail",
    "default-system": "SendGridMailSystem",
    "user_import": "DefaultMailSystem",
    "uc_cart": "UbercartMailSystem",
    "uc_order": "UbercartMailSystem",
    "uc_file": "UbercartMailSystem",
    "uc_roles": "UbercartMailSystem",
    "uc_stock": "UbercartMailSystem",
    "uc_store": "UbercartMailSystem",
    "mimemail": "MimeMailSystem",
    "mail_system": {
        "default-system": "SendGridMailSystem"
    }
}

therefore it would appear "default-system": "MimeMailSystem" is the problem stopping Maillog.

**Comment by argiepiano** [comment]
The json file looks weird to me, especially the fact that you have a `mail_system` key and two `default-system` keys at differentI levels. Are you using the latest version of Mail System and Mimemail? I'm wondering if SendGrid is messing up that config file. I see that sendgrid_integration doesn't have a release, and the latest commits are 2 years old. The maintainer doesn't seem active... so perhaps that module is creating the issues.

This is typically the content of the json file with Mail System, Maillog, MimeMail and Ubercart all installed:

```json
{
    "_config_name": "system.mail",
    "default-system": "MailsystemDelegateMailSystem",
    "mimemail": "MimeMailSystem",
    "uc_cart": "UbercartMailSystem",
    "uc_order": "UbercartMailSystem",
    "uc_file": "UbercartMailSystem",
    "uc_roles": "UbercartMailSystem",
    "uc_stock": "UbercartMailSystem",
    "uc_store": "UbercartMailSystem"
}
```

Notice the `MailsystemDelegateMailSystem`. This is a wrapper class provided by Mail System that allows you to choose different classes for formatting and delivery. In my settings I have selected:

<img width="542" alt="Screen Shot 2023-08-27 at 10 07 23 PM" src="https://github.com/backdrop-contrib/maillog/assets/9938978/34c2562d-2d08-4ded-98c2-9fdbf29f1a3a">

**Comment by onyxnz** [comment]
hmmm. Trying your settings, I get: Class <em class="placeholder">MailsystemDelegateMailSystem</em> does not implement interface <em class="placeholder">MailSystemInterface</em>

**Comment by argiepiano** [comment]
To clarify, I did not modify the settings manually - that's the settings that you get when you have Mail System, Maillog, MimeMail and Ubercart all installed and you select the settings I pasted above in the UI. So, my suspicion is that SendGrid is messing those up. Unfortunately, uninstalling it will not fix the settings - you would have to uninstall all the modules I mentioned above, and copy the pristine system.mail.json file from core/modules/system/config manually, and then reinstall the mail-related modules, minus SendGrid

**Comment by argiepiano** [comment]
OK, a bit of digging. It looks like the key `mail_system` was used by mailsystem in D7, and it's created during `mailsystem_update_1000()` for D7 upgrades, but not for clean installs. This is problematic, as the structure of the config file has changed, and that key doesn't do anything. 

So that particular key is basically ignored by Backdrop. It's still unclear if this is related to your issues here.

I'll open an issue both in Ubercart (which also uses it) and Mailsystem

**Comment by argiepiano** [comment]
Actually, no. Mailsystem moves that variable to the correct key (`default-system`). The problem is uc_store.

**Comment by argiepiano** [comment]
Wrong again! Both Ubercart and Mailsystem do this correctly. Hmmm.... My next question is: did you add the key/value `mail_system` manually yourself? Otherwise I can't tell where it came from.

**Comment by argiepiano** [comment]
OK, sorry for the repeated messages. I found it. As suspected, SendGrid Integration is doing this.. wrongly, and messing up the config file.

**Comment by onyxnz** [comment]
I hadn't modified anything myself, and had no clue where to look until you started pointing me there :-)
So Sendgrid Integration is the issue? If so, what should my config be if I need SendGrid and MimeMail? 

Currently I have everything running to send via SendGrid, but the emails are plaintext only.
{
    "_config_name": "system.mail",
    "default-system": "SendGridMailSystem",
    "mimemail": "MimeMailSystem",
    "uc_cart": "UbercartMailSystem",
    "uc_order": "UbercartMailSystem",
    "uc_file": "UbercartMailSystem",
    "uc_roles": "UbercartMailSystem",
    "uc_stock": "UbercartMailSystem",
    "uc_store": "UbercartMailSystem"
}

**Comment by argiepiano** [comment]
So, I *think* the trick here is to allow Mail System to take over. So, `default-system` should be `"MailsystemDelegateMailSystem"'  (be sure mailsystem is actually enabled, otherwise that class will not be found). You will need to manually edit that.

Then you will need to go to `admin/config/system/mailsystem` and select "Mime Mail" for "Formatting:" in "Site-wide default mail system" (this will assure you send html emails), and select "SendGrid" for "Delivery", so that emails are delivery through that. 

I have no way of testing this since I don't have a SendGrid account. 

As for the issues with SendGrid...

**Comment by argiepiano** [comment]
Maybe we should continue this conversation somewhere else :) We are filling this issue for maillog, which is not the culprit of the problems.

**Comment by onyxnz** [comment]
Thanks again. Will come back to you when I discover why MailSystem white screens the site. Am about to demonstrate to stakeholders :-O
